### ISSUE TITLE
Program cannot run with setting CUDA_CORE_LIMIT

### ISSUE THREAD

**Issue by LiDaiyan** [mYmNeo/nv-resource-controller#3]
After setting **CUDA_CORE_LIMIT** and **CUDA_MEM_LIMIT** and **LD_PRELOAD** , the every program or command line cannot run just wait. When I unset **CUDA_CORE_LIMIT** , the every program and command can run but with a log:

> /home/user/nv-resource-controller/src/env.c:22 env CUDA_CORE_LIMIT not found

besides, the mem limit is right.

so what cause the issue and how can i solve it?

Thanks for your project!

**Comment by mYmNeo** [comment]
See the README, you must have a server_monitor running
